insert into public.businesses (
  name,
  slug,
  category,
  description,
  address,
  latitude,
  longitude,
  video_link,
  website_url,
  instagram_url,
  facebook_url,
  images,
  faqs,
  features,
  status,
  listing_tier,
  active_plan_id,
  payment_status,
  paid_until,
  is_homepage_spotlight,
  homepage_spotlight_until,
  priority,
  map_pin_x,
  map_pin_y,
  show_on_illustrated_map,
  seo_title,
  seo_description
)
values
  (
    'Bansko Art Studio',
    'bansko-art-studio-demo',
    'Култура',
    'Демо spotlight профил за визуални услуги, fine art печат и авторски продукти, вдъхновени от Банско и Пирин.',
    'ул. Пирин, Банско',
    41.8388,
    23.4892,
    'https://www.youtube.com/embed/ysz5S6PUM-U',
    'https://bansko.now/art-studio',
    null,
    null,
    array[
      'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?auto=format&fit=crop&w=1200&q=80'
    ],
    '[{"question":"Може ли да се поръча печат на платно?","answer":"Да, профилът е примерен и показва как ще изглеждат FAQ въпросите в бизнес страницата."}]'::jsonb,
    array['Плащане с карта', 'Английски език', 'Работи целогодишно'],
    'approved',
    'homepage',
    (select id from public.business_listing_plans where slug = 'homepage-spotlight-1-month'),
    'paid',
    '2027-07-01T00:00:00+00',
    true,
    '2027-07-01T00:00:00+00',
    1,
    48,
    45,
    true,
    'Bansko Art Studio | Bansko NOW',
    'Демо spotlight бизнес профил в Bansko NOW с видео, снимки, FAQ и упътване.'
  ),
  (
    'Pirin Garden Restaurant',
    'pirin-garden-restaurant-demo',
    'Ресторанти',
    'Демо premium ресторант с по-голяма карта в каталога, снимкова галерия и видимо позициониране в категорията.',
    'център, Банско',
    41.8377,
    23.4883,
    null,
    null,
    null,
    null,
    array[
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80'
    ],
    '[{"question":"Има ли тераса?","answer":"Да, това е пример за feature и FAQ визуализация."}]'::jsonb,
    array['Wi-Fi', 'Плащане с карта', 'Тераса', 'Подходящо за семейства'],
    'approved',
    'premium',
    (select id from public.business_listing_plans where slug = 'premium-6-months'),
    'paid',
    '2027-01-01T00:00:00+00',
    false,
    null,
    5,
    52,
    50,
    true,
    'Pirin Garden Restaurant в Банско | Bansko NOW',
    'Демо premium ресторант в бизнес каталога на Bansko NOW.'
  ),
  (
    'Old Town Coffee',
    'old-town-coffee-demo',
    'Кафета',
    'Демо featured кафе за сутрешно кафе, работа с лаптоп и спокойна градска атмосфера.',
    'Старият град, Банско',
    41.8369,
    23.4868,
    null,
    null,
    null,
    null,
    array[
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1400&q=80'
    ],
    '[{"question":"Подходящо ли е за работа?","answer":"Да, feature таговете могат да показват Wi-Fi и плащане с карта."}]'::jsonb,
    array['Wi-Fi', 'Плащане с карта', 'Pet friendly'],
    'approved',
    'featured',
    (select id from public.business_listing_plans where slug = 'featured-1-month'),
    'paid',
    '2026-12-01T00:00:00+00',
    false,
    null,
    12,
    41,
    42,
    true,
    'Old Town Coffee в Банско | Bansko NOW',
    'Демо featured кафе в бизнес каталога на Bansko NOW.'
  ),
  (
    'Bansko Mountain Guide',
    'bansko-mountain-guide-demo',
    'Активности',
    'Демо free профил за планински водач, маршрути и идеи за Пирин.',
    'Банско',
    41.8391,
    23.4848,
    null,
    null,
    null,
    null,
    array[
      'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?auto=format&fit=crop&w=1400&q=80'
    ],
    '[{"question":"Има ли маршрути за начинаещи?","answer":"Да, FAQ секцията е подходяща за кратки практически отговори."}]'::jsonb,
    array['Английски език', 'Подходящо за семейства', 'Работи целогодишно'],
    'approved',
    'free',
    null,
    'unpaid',
    null,
    false,
    null,
    40,
    58,
    34,
    true,
    'Bansko Mountain Guide | Bansko NOW',
    'Демо free бизнес профил за активности и планински услуги в Банско.'
  )
on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  address = excluded.address,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  video_link = excluded.video_link,
  website_url = excluded.website_url,
  instagram_url = excluded.instagram_url,
  facebook_url = excluded.facebook_url,
  images = excluded.images,
  faqs = excluded.faqs,
  features = excluded.features,
  status = excluded.status,
  listing_tier = excluded.listing_tier,
  active_plan_id = excluded.active_plan_id,
  payment_status = excluded.payment_status,
  paid_until = excluded.paid_until,
  is_homepage_spotlight = excluded.is_homepage_spotlight,
  homepage_spotlight_until = excluded.homepage_spotlight_until,
  priority = excluded.priority,
  map_pin_x = excluded.map_pin_x,
  map_pin_y = excluded.map_pin_y,
  show_on_illustrated_map = excluded.show_on_illustrated_map,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  updated_at = now();

delete from public.business_contacts
where business_id in (
  select id
  from public.businesses
  where slug in (
    'bansko-art-studio-demo',
    'pirin-garden-restaurant-demo',
    'old-town-coffee-demo',
    'bansko-mountain-guide-demo'
  )
);

insert into public.business_contacts (business_id, owner_name, owner_phone, owner_email)
select id, 'Demo Owner', '+359 000 000 000', 'demo@bansko.now'
from public.businesses
where slug in (
  'bansko-art-studio-demo',
  'pirin-garden-restaurant-demo',
  'old-town-coffee-demo',
  'bansko-mountain-guide-demo'
);
